### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by hoochanlon** [Cyberbolt/cfw#5]
要不参考这个老外写的项目[anti-ddos/Anti-DDOS](https://github.com/anti-ddos/Anti-DDOS)，我看了脚本代码，大部分功能基本上也是iptables完成的，我在这里就不重复了，他的脚本代码注释写得挺清楚的，可读性很不错。

**Comment by omaidb** [comment]
@Cyberbolt 发现不能放行或者阻止一组端口段。

**Comment by Potato-OvO** [comment]
@omaidb 感谢您的建议，后续我们会对该功能进行添加补充

**Comment by omaidb** [comment]
@Potato-OvO 可否将.py文件编译下，运行时间长了内存占用较高，1G小机器死机了。
另外，可否自动创建个/etc/sysctl.d/cfw.conf文件，配置最优的抗DDOS的配置。
参考2: [https://developer.aliyun.com/article/52268](https://developer.aliyun.com/article/52268)
参考1:[https://blog.csdn.net/omaidb/article/details/122719243](https://blog.csdn.net/omaidb/article/details/122719243)
