### ISSUE TITLE
优化建议:编译python文件

### ISSUE THREAD

**Issue by omaidb** [Cyberbolt/cfw#7]
可否将.py文件编译下，提高运行效率

**Comment by Potato-OvO** [comment]
感谢您的意见。

我们的软件CFW没有编译python，使用的是我们直接下载好的python的标准的二进制文件，并且我们使用的是固定的 python3.9的环境。CFW调用的是iptables，性能部分由iptables保障，我们可以减少对语言性能的关注。

我们会持续关注项目中的问题，如果您还有任何疑问、建议或意见，请随时与我们联系，我们将非常乐意为您提供帮助。
