### ISSUE TITLE
优化建议:配置sysctl抗DDOS

### ISSUE THREAD

**Issue by omaidb** [Cyberbolt/cfw#8]
优化建议2:
可否自动创建个/etc/sysctl.d/cfw.conf文件，配置最优的抗DDOS的配置。
参考2: https://developer.aliyun.com/article/52268
参考1:https://blog.csdn.net/omaidb/article/details/122719243
参考0:[https://zhuanlan.zhihu.com/p/487249503](https://zhuanlan.zhihu.com/p/487249503)

**Comment by Potato-OvO** [comment]
感谢您对我们项目的持续关注。

CFW自带抗DDOS的功能，不需要额外的配置。根据您提供的参考，sysctl主要用于调整操作系统内核的参数，虽然也可以做到抗DDOS的功能，但他不支持开关端口。而CFW主要是由iptables和ipset实现，iptables 主要是用于配置防火墙规则的工具，它允许你控制进出系统的网络流量，且可以实现端口开关的控制。基于以上我们选择了使用iptables。iptabesl很强大，我们配置的规则也许不是最好，如有更好的配置规则或有理解不到位的地方欢迎继续交流。

我们会持续关注项目中的问题，如果您还有任何疑问、建议或意见，请随时与我们联系，我们将非常乐意为您提供帮助。
