### ISSUE TITLE
优化建议:增加cfw update升级命令

### ISSUE THREAD

**Issue by omaidb** [Cyberbolt/cfw#9]
优化建议:
前面提交了unblock_time设为0后cfw无法启动 的Bug，解决方案是卸载重装，个人感觉这不是一个很好的解决方案。
建议增加cfw update升级命令，来完成升级。
虽然这个cfw update很可能就是封装了卸载重装的过程，但是从用户侧感觉会友好很多。

**Comment by Potato-OvO** [comment]
感谢您的建议，CFW已经增加了升级命令。

CFW任何版本可使用`sudo curl https://raw.githubusercontent.com/Cyberbolt/cfw/main/update.py | python3`进行升级（主要兼容老版本）
或
CFW版本大于等于v1.0.3可使用`cfw update`对软件进行升级

我们会持续关注项目中的问题，如果您还有任何疑问、建议或意见，请随时与我们联系，我们将非常乐意为您提供帮助。
